spring:
  jpa:
    database: MySQL
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 1000
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
  banner:
    location: banner.txt

    # 配置MyBatis日志 mybatis-plus: configuration: log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl