spring:
  jpa:
    database: MySQL
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 1000
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
  banner:
    location: banner.txt
social-month-template-path: "/template/社保月度报表导出模板.xlsx"
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
