server:
  port: 9005
  servlet:
    encoding:
      force-response: true
# 日志配置
logging:
  level:
    root: info
  file:
    name: "./logs/attendance-dev.log"
  pattern:
    #日志输出的颜色：blue cyan faint green magenta red yellow
    console: "%clr(%d{yyyy/MM/dd-HH:mm:ss}){blue} [%t] %clr(%-5p) %clr(%c{30}){cyan} : %clr(%m){magenta}%n"
  logback:
    rollingpolicy:
      file-name-pattern: attendance.%d{yyyy-MM-dd}.%i.log
      max-file-size: 10MB
