server:
  port: 9001
spring:
  application:
    name: hrm-company #指定服务名
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.182.129:33306/db_hrm?useSSL=true&useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&serverTimezone=Asia/Shanghai
    username: root
    password: 991226Ab#
  jpa:
    database: MySQL
    show-sql: true
    open-in-view: true
  banner:
    location: banner.txt
  redis:
    host: 192.168.182.129
    port: 6379
logging:
  level:
    root: info
  file:
    name: company.log
#微服务注册到eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://192.168.182.129:6868/eureka/
