server:
  port: 9999
spring:
  application:
    name: hrm-gateway
  redis:
    host: 43.138.155.170
    port: 6379
    password: 123456
  cloud:
    nacos:
      server-addr: 43.138.155.170:80
      discovery:
        server-addr: 43.138.155.170:80
    gateway:
      globalcors: # 全局的跨域处理
        add-to-simple-url-handler-mapping: true  # 解决options请求被拦截
        cors-configurations:
          '[/**]':
            allowedOrigins: # 允许的请求
              - "http://localhost:8080"
              - "http://119.39.96.34:8080"
              - "http://10.151.12.131:8080"
            allowedMethods:
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许携带头信息
            allowCredentials: true # 允许携带cookie
            maxAge: 36000 # 跨域有效期
      routes: # 路由配置
        - id: hrm-system
          uri: lb://hrm-system
          predicates: # 路由断言
            - Path=/sys/**
        - id: hrm-company
          uri: lb://hrm-company
          predicates: # 路由断言
            - Path=/company/**
        - id: hrm-employee
          uri: lb://hrm-employee
          predicates: # 路由断言
            - Path=/employees/**
        - id: hrm-social-security
          uri: lb://hrm-social-security
          predicates: # 路由断言
            - Path=/social/**
  banner:
    location: banner.txt