spring:
  jpa:
    database: MySQL
    show-sql: true
    open-in-view: true
  banner:
    location: banner.txt
feign:
  httpclient:
    enabled: true
    max-connections: 50
  client:
    config:
      default:
        loggerLevel: BASIC

