spring:
  application:
    name: hrm-system #指定服务名
  jpa:
    database: MySQL
    show-sql: true
    open-in-view: true
  banner:
    location: banner.txt
  profiles:
    active: dev
    # 现在dev和pro使用的同一套配置，在生产环境会改变
    group:
      "dev": devDB,devRedis,devEureka,devFileUpload
      "pro": devDB,devRedis,devEureka,devFileUpload
# 自定义配置
# 初始化密码123456
initial-password: e10adc3949ba59abbe56e057f20f883e
